name: MPI Tests

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  mpi-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar MPI
        run: |
          sudo apt-get update
          sudo apt-get install -y mpich

      # ---------- TESTE ATIVIDADE 2 ----------
      - name: Compilar Atividade 2
        run: |
          mpicc media_mpi.c -o media_mpi

      - name: Executar Atividade 2
        run: |
          mpirun -np 4 ./media_mpi 1000

      # ---------- TESTE ATIVIDADE 3 ----------
      - name: Compilar Atividade 3
        run: |
          mpicc atividade3.c -o atividade3

      - name: Executar Atividade 3
        run: |
          mpirun -np 5 ./atividade3
